### ISSUE TITLE
SEO site heading and site description does not appear in Browser heading and tab

### ISSUE THREAD

**Issue by thijskrooswijk** [wheelroom/wheelroom#79] opened 2020-04-29 09:05 UTC
1. Run `npm develop`
2. Visit the homepage or any other page
3. Look at your web browser (e.g. Chrome, Firefox or Safari)
4. The heading is showing the URL instead of the SEO site heading and site description

**Comment by jaccomeijer** [comment] 2020-04-29 09:28
Please add 'steps to reproduce' in the description, all issues should have that.

**Comment by jaccomeijer** [comment] 2020-04-29 09:34
This is probably because of they way Helmet works:
https://github.com/nfl/react-helmet

My guess is that it works properly once deployed on Netlify. Can you check?

**Comment by jaccomeijer** [comment] 2020-04-29 16:53
Closing this because the page seo title was not set.

**Closed by jaccomeijer** 2020-04-29 16:53 UTC
Labels: bug, question
